# basic options
title: Mida
author: Mida
email: midanwrk@gmail.com
description: A wonderful site
twitter_username: ademideo_
github_username:  midanet

# Build settings
markdown: kramdown
theme: minima
